window.DND_ASSETS = {
 "dwarf": "assets/dwarf.webp",
 "elf": "assets/elf.webp",
 "drow": "assets/drow.webp",
 "halfelf": "assets/halfelf.webp",
 "halfling": "assets/halfling.webp",
 "human": "assets/human.webp",
 "dragonborn": "assets/dragonborn.webp",
 "gnome": "assets/gnome.webp",
 "orc": "assets/orc.webp",
 "tiefling": "assets/tiefling.webp",
 "aasimar": "assets/aasimar.webp",
 "kenku": "assets/kenku.webp",
 "aarakocra": "assets/aarakocra.webp",
 "gnoll": "assets/gnoll.webp",
 "kobold": "assets/kobold.webp",
 "genasi": "assets/genasi.webp",
 "goblin": "assets/goblin.webp",
 "firbolg": "assets/firbolg.webp",
 "triton": "assets/triton.webp",
 "tabaxi": "assets/tabaxi.webp",
 "giant": "assets/giant.webp",
 "goliath": "assets/goliath.webp",
 "centaur": "assets/centaur.webp",
 "warforged": "assets/warforged.webp",
 "misc": "assets/misc.webp"
};
