window.DND_ASSETS = {
 "dwarf": "assets/dwarf.jpg",
 "elf": "assets/elf.jpg",
 "drow": "assets/drow.jpg",
 "halfelf": "assets/halfelf.jpg",
 "halfling": "assets/halfling.jpg",
 "human": "assets/human.jpg",
 "dragonborn": "assets/dragonborn.jpg",
 "gnome": "assets/gnome.jpg",
 "orc": "assets/orc.jpg",
 "tiefling": "assets/tiefling.jpg",
 "aasimar": "assets/aasimar.jpg",
 "kenku": "assets/kenku.jpg",
 "aarakocra": "assets/aarakocra.jpg",
 "gnoll": "assets/gnoll.jpg",
 "kobold": "assets/kobold.jpg",
 "genasi": "assets/genasi.jpg",
 "goblin": "assets/goblin.jpg",
 "firbolg": "assets/firbolg.jpg",
 "triton": "assets/triton.jpg",
 "tabaxi": "assets/tabaxi.jpg",
 "giant": "assets/giant.jpg",
 "goliath": "assets/goliath.jpg",
 "centaur": "assets/centaur.jpg",
 "warforged": "assets/warforged.jpg",
 "misc": "assets/misc.jpg"
};
